package com.almubaraksuleiman.cbts.proctor.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing a Proctor in the CBTS (Computer-Based Test System).

 * Proctors are responsible for monitoring exams in real-time, ensuring academic integrity,
 * and preventing cheating during test sessions. This entity stores proctor authentication
 * credentials, account status, and monitoring capabilities.

 * Includes comprehensive validation for data integrity, security, and monitoring requirements.
 *
 * @author Almubarak Suleiman
 * @version 1.0
 * @since 2025
 */
@Entity
@Table(name = "proctor") // Maps to "proctor" table in database
@Data // Lombok: Generates getters, setters, toString, equals, and hashCode
@NoArgsConstructor // Lombok: Generates no-args constructor
@AllArgsConstructor // Lombok: Generates all-args constructor
public class Proctor {

    /**
     * Primary key identifier for the Proctor entity.
     * Uses database identity generation for automatic ID assignment.
     *
     * @apiNote Automatically generated by the database upon persistence
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique username for proctor authentication and identification.
     * Must be unique across all proctor accounts and cannot be null.
     *
     * @constraint 4-20 characters, alphanumeric with optional underscores
     * @businessRule Usernames should be professional and easily identifiable during monitoring
     */
    @NotBlank(message = "Username is required")
    @Size(min = 4, max = 20, message = "Username must be between 4 and 20 characters")
    @Pattern(regexp = "^[a-zA-Z0-9_]+$",
            message = "Username can only contain letters, numbers, and underscores")
    @Column(unique = true, nullable = false, length = 20)
    private String username;

    /**
     * Hashed password for proctor authentication.
     * Stores BCrypt-hashed password for secure authentication.
     *
     * @security Always stored in hashed format using BCrypt
     * @note Validation applies to raw password before hashing in DTO
     * @important Proctors require strong passwords due to exam monitoring privileges
     */
    @NotBlank(message = "Password is required")
    @Column(unique = true, nullable = false, length = 100) // BCrypt hash length + buffer
    private String password;

    /**
     * Account verification status flag.
     * Indicates whether the proctor's account has been verified and trained.
     * Defaults to false upon account creation and requires training completion.
     *
     * @default false (unverified upon account creation)
     */
    @Column(nullable = false)
    private boolean verified = false;

    /**
     * Unique email address for the proctor.
     * Used for urgent communications, alert notifications, and account recovery.
     * Must be unique across all proctor accounts and cannot be null.
     *
     * @constraint Valid email format, unique across system
     * @businessRule Reliable email required for urgent exam monitoring alerts
     */
    @NotBlank(message = "Email is required")
    @Email(message = "Email must be a valid email address format",
            regexp = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$")
    @Column(unique = true, nullable = false, length = 100)
    private String email;


    @Column
    String firstName;

    @Column
    String middleName;

    @Column
    String lastName;

    @Column
    String department;


}