package com.almubaraksuleiman.cbts.proctor.model;

public enum ViolationType {
    MULTIPLE_FACES_DETECTED,
    NO_FACE_DETECTED,
    FACE_NOT_VISIBLE,
    PHONE_DETECTED,
    PERSON_ENTERED_ROOM,
    VOICE_DETECTED,
    EYE_MOVEMENT_SUSPICIOUS,
    HEAD_MOVEMENT_SUSPICIOUS,
    BROWSER_SWITCH,
    UNAUTHORIZED_APPLICATION,
    COPY_PASTE_DETECTED,
    SCREENSHOT_DETECTED
}
