// Package declaration - organizes classes within the student model package
package com.almubaraksuleiman.cbts.student.model;

// Import statements - JPA annotations, Lombok utilities, and related entities
import com.almubaraksuleiman.cbts.examiner.model.Question;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a student's answer to a specific question in an exam.
 * This entity stores the actual answer provided by the student along with
 * the scoring information for that particular answer.

 * This can be used for tracking answer history, versioning, or detailed
 * answer analysis beyond the basic response stored in StudentExamQuestion.
 * @author Almubarak Suleiman
 * @version 1.0
 * @since 2025
 **/

@Entity // Marks this class as a JPA entity (persistent domain object)
@Table(name = "student_answers") // Specifies the database table name
@Data // Lombok: generates getters, setters, toString, equals, and hashCode methods
@NoArgsConstructor // Lombok: generates a no-arguments constructor
@AllArgsConstructor // Lombok: generates a constructor with all fields as arguments
@Builder // Lombok: enables the builder pattern for object creation
public class StudentAnswer {

    /**
     * Unique identifier for the student answer record.
     * Auto-generated by the database using identity column strategy.
     * This is the primary key of the student_answers table.
     */
    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-increment strategy
    private Long id;

    /**
     * The exam question instance that this answer belongs to.
     * Many-to-One relationship: Many answer records can belong to one exam question.
     * Uses lazy fetching to improve performance.
     * This links to the StudentExamQuestion which contains the session-question relationship.
     */
    @ManyToOne(fetch = FetchType.LAZY) // Many answers to one exam question instance
    @JoinColumn(name = "student_exam_question_id", nullable = false) // Foreign key, not null
    private StudentExamQuestion studentExamQuestion;

    /**
     * [Experimental] Direct reference to the exam session.
     * This is being tested as an additional relationship to potentially
     * simplify queries or provide alternative access paths.
     * Many-to-One relationship: Many answers can belong to one exam session.
     */
    @ManyToOne(fetch = FetchType.LAZY) // Many answers to one exam session
    @JoinColumn(name = "session_id", nullable = false) // Foreign key, not null
    private StudentExam studentExam;

    /**
     * [Experimental] Direct reference to the question.
     * This is being tested as an additional relationship to potentially
     * simplify queries or provide alternative access paths.
     * Many-to-One relationship: Many answers can reference one question.
     */
    @ManyToOne(fetch = FetchType.LAZY) // Many answers to one question
    @JoinColumn(name = "question_id", nullable = false) // Foreign key, not null
    private Question question;

    /**
     * The actual answer provided by the student.
     * Storage format depends on the question type:
     * - Multiple Choice: Selected option (e.g., "Option C")
     * - Multiple Select: Comma-separated selected options (e.g., "A,C,D")
     * - Fill in the Blank: Text response
     * - Essay: Longer text response

     * This field stores the final or most recent answer submission.
     */
    private String answer;

    /**
     * The score awarded for this specific answer.
     * Represents the points earned for this question response.
     * For auto-graded questions: calculated automatically
     * For manually graded questions: entered by the instructor
     * Null if the question hasn't been graded yet.
     */
    private Double score;

    /*
     * Potential additional fields that could be added:

     * // Timestamp when the answer was submitted
     * private LocalDateTime submittedAt;

     * // Version number for tracking answer revisions
     * private Integer version = 1;

     * // Whether this is the final submitted answer
     * private Boolean finalAnswer = false;

     * // Confidence level self-reported by student (1-5 scale)
     * private Integer confidenceLevel;

     * // Time taken to answer this question (in seconds)
     * private Integer timeSpentSeconds;

     * // Feedback comments from grader (for manual grading)
     * private String graderFeedback;

     * // Whether the answer was changed from previous attempts
     * private Boolean answerChanged = false;

     * // Partial credit details for complex scoring
     * private String scoringDetails;
     */

    /*
     * Helper methods that could be added:

     * // Check if the answer is correct (for auto-graded questions)
     * public boolean isCorrect() {
     *     if (question != null && answer != null) {
     *         return answer.equals(question.getCorrectAnswer());
     *     }
     *     return false;
     * }

     * // Calculate the score percentage for this question
     * public Double getScorePercentage() {
     *     if (score != null && question != null && question.getMaxMarks() != null) {
     *         return (score / question.getMaxMarks()) * 100;
     *     }
     *     return null;
     * }

     * // Get answer as list for multiple select questions
     * public List<String> getAnswerAsList() {
     *     if (answer == null || answer.isEmpty()) {
     *         return new ArrayList<>();
     *     }
     *     return Arrays.asList(answer.split(","));
     * }

     * // Set answer from list for multiple select questions
     * public void setAnswerFromList(List<String> answers) {
     *     this.answer = String.join(",", answers);
     * }
     */

    /*
     * Example of builder pattern usage:
     * StudentAnswer studentAnswer = StudentAnswer.builder()
     *     .studentExamQuestion(examQuestion)
     *     .studentExam(examSession)
     *     .question(mathQuestion)
     *     .answer("3.14")
     *     .score(1.0)
     *     .build();
     */
}