package com.almubaraksuleiman.cbts.examiner.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing an Examiner in the CBTS (Computer-Based Test System).

 * Examiners are responsible for creating, managing, and grading exams within the system.
 * This entity stores examiner authentication credentials and account status information.

 * Includes comprehensive validation for data integrity, security, and business rules.
 *
 * @author Almubarak Suleiman
 * @version 1.0
 * @since 2025
 */
@Entity
@Table(name = "examiner") // Maps to "examiner" table in database
@Data // Lombok: Generates getters, setters, toString, equals, and hashCode
@NoArgsConstructor // Lombok: Generates no-args constructor
@AllArgsConstructor // Lombok: Generates all-args constructor
public class Examiner {

    /**
     * Primary key identifier for the Examiner entity.
     * Uses database identity generation for automatic ID assignment.
     *
     * @apiNote Automatically generated by the database upon persistence
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique username for examiner authentication and identification.
     * Must be unique across all examiner accounts and cannot be null.
     *
     * @constraint 3-20 characters, alphanumeric with optional underscores and dots
     * @businessRule Usernames should be professional and easily identifiable
     */
    @NotBlank(message = "Username is required")
    @Size(min = 3, max = 20, message = "Username must be between 3 and 20 characters")
    @Pattern(regexp = "^[a-zA-Z0-9_.]+$",
            message = "Username can only contain letters, numbers, underscores, and dots")
    @Column(unique = true, nullable = false, length = 20)
    private String username;

    /**
     * Hashed password for examiner authentication.
     * Stores BCrypt-hashed password for secure authentication.
     *
     * @security Always stored in hashed format using BCrypt
     * @note Validation applies to raw password before hashing in DTO
     */
    @NotBlank(message = "Password is required") // Validates non-null and non-empty
    @Column(unique = true, nullable = false, length = 100) // BCrypt hash length + buffer
    private String password;

    /**
     * Account verification status flag.
     * Indicates whether the examiner's account has been verified and activated.
     * Defaults to false upon account creation and must be set to true after verification.
     *
     * @default false (unverified upon account creation)
     * @businessRule Examiners require account verification before accessing system features
     */
    @Column(nullable = false)
    private boolean verified = false;

    /**
     * Unique email address for the examiner.
     * Used for official communication, notifications, and account recovery.
     * Must be unique across all examiner accounts and cannot be null.
     *
     * @constraint Valid email format, unique across system
     * @businessRule Professional email address required for official communications
     */
    @NotBlank(message = "Email is required")
    @Email(message = "Email must be a valid email address format",
            regexp = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$")
    @Column(unique = true, nullable = false, length = 100)
    private String email;


    @Column
    String firstName;

    @Column
    String middleName;

    @Column
    String lastName;


    @Column
    String department;

    @Column(name = "profile_image_url")
    private String profileImageUrl;

}