//// Package declaration - organizes classes within the model package
//package com.almubaraksuleiman.cbts.examiner.model;
//
//// Import statements - JPA annotations, Lombok utilities, and Jackson for JSON handling
//import com.fasterxml.jackson.annotation.JsonIgnore;
//import jakarta.persistence.*;
//import lombok.*;
//
//import java.util.ArrayList;
//import java.util.List;
//import java.util.stream.Collectors;
//
///**
// * Represents a single question within a test in the Computer-Based Test (CBT) system.
// * Each question contains the question text, answer choices, correct answer, scoring information,
// * and maintains a relationship with its parent test.
//
// * This entity is mapped to the "questions" table in the database and uses JPA annotations
// * for object-relational mapping along with Lombok for boilerplate code reduction.
// *
// * @author Almubarak Suleiman
// * @version 1.0
// * @since 2025
// **/
//
//
//@Entity // Marks this class as a JPA entity (persistent domain object)
//@Table(name = "questions") // Specifies the database table name
//@Data // Lombok: generates getters, setters, toString, equals, and hashCode methods
//@NoArgsConstructor // Lombok: generates a no-arguments constructor
//@AllArgsConstructor // Lombok: generates a constructor with all fields as arguments
//@Builder // Lombok: enables the builder pattern for object creation
//public class Question {
//
//    /**
//     * Unique identifier for the question.
//     * Auto-generated by the database using identity column strategy.
//     * This is the primary key of the questions table.
//     */
//    @Id // Marks this field as the primary key
//    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-increment strategy
//    private Long id;
//
//    /**
//     * The actual question text or prompt presented to the student.
//     * Contains the problem, scenario, or query that the student must address.
//     * This field should be clear, unambiguous, and complete.
//     */
//    private String text;
//
//    /**
//     * The available answer choices for the question.
//     * Typically stored as a JSON string or comma-separated values.
//     * Example formats:
//     * - JSON: ["Option A", "Option B", "Option C", "Option D"]
//     * - CSV: "Option A,Option B,Option C,Option D"
//
//     * For multiple choice questions, this contains all possible options.
//     * For true/false questions, this might contain ["True", "False"].
//     */
//    //@Lob // Could be used for large text content (commented out but available)
//    private String choices; // JSON string or comma-separated values representing answer options
//
//    /**
//     * The correct answer to the question.
//     * This should match one of the values in the choices field exactly.
//     * For multiple choice: the correct option text (e.g., "Option C")
//     * For true/false: either "True" or "False"
//     * For short answer: the exact expected answer
//     */
//    private String correctAnswer;
//
//    /**
//     * The type of question, determining how it should be presented and evaluated.
//     * Uses the QuestionType enum to enforce valid question types.
//     * Defaults to MULTIPLE_CHOICE for convenience.
//     */
//    @Enumerated(EnumType.STRING) // Store enum values as strings in database
//    private QuestionType type = QuestionType.MULTIPLE_CHOICE; // Default question type
//
//    /**
//     * The maximum marks or points awarded for answering this question correctly.
//     * Used in score calculation and grading.
//     * Defaults to 1.0 point for standard questions.
//     */
//    private Double maxMarks; //= 1.0; // Default maximum marks
//
//    /**
//     * The test that this question belongs to.
//     * Many-to-One relationship: Many questions can belong to one test.
//     * Uses lazy fetching to improve performance (data loaded only when accessed).
//     * The foreign key column "test_id" cannot be null, ensuring every question has a parent test.
//
//     * JsonIgnore prevents circular references during JSON serialization.
//     * ToString.Exclude prevents infinite loops in toString() method.
//     */
//    @ManyToOne(fetch = FetchType.LAZY) // Many questions to one test relationship with lazy loading
//    @JoinColumn(name = "test_id", nullable = false) // Foreign key column with not-null constraint
//    @ToString.Exclude // Lombok: exclude from toString() to prevent circular references
//    @JsonIgnore // Jackson: ignore during JSON serialization to prevent circular references
//    private Test test;
//
//
//    /**
//     * Media type for the question
//     * Values: IMAGE, VIDEO, AUDIO, NONE
//     */
//    @Enumerated(EnumType.STRING)
//    private MediaType mediaType;
//
//    /**
//     * Media file path or URL
//     * For images: "/uploads/images/question1.jpg"
//     * For video: "/uploads/videos/demo.mp4"
//     * For audio: "/uploads/audio/explanation.mp3"
//     */
//    private String mediaPath;
//
//    /**
//     * Media caption or description
//     */
//    private String mediaCaption;
//
//
//
//    /*
//     * Potential additional fields that could be added:
//
//     * // Difficulty level of the question
//     * @Enumerated(EnumType.STRING)
//     * private DifficultyLevel difficulty;
//
//     * // Explanation of the correct answer (for review purposes)
//     * private String explanation;
//
//     * // Question category or topic
//     * private String category;
//
//     * // Time limit for this specific question (overrides test duration)
//     * private Integer timeLimitSeconds;
//
//     * // Order or sequence number within the test
//     * private Integer questionOrder;
//
//     * // Flag for whether this question is active/available
//     * private Boolean active = true;
//
//     * // Timestamp for when the question was created
//     * @CreationTimestamp
//     * private LocalDateTime createdAt;
//
//     * // Timestamp for when the question was last modified
//     * @UpdateTimestamp
//     * private LocalDateTime updatedAt;
//     */
//
//    /*
//     * Example of builder pattern usage:
//     * Question mathQuestion = Question.builder()
//     *     .text("What is the value of π (pi) to two decimal places?")
//     *     .choices("3.14,3.41,3.16,3.18")
//     *     .correctAnswer("3.14")
//     *     .type(QuestionType.MULTIPLE_CHOICE)
//     *     .maxMarks(1.0)
//     *     .test(parentTest)
//     *     .build();
//     */
//
//    /*
//     * Helper method to get choices as list (could be added):
//     * public List<String> getChoicesAsList() {
//     *     return Arrays.asList(choices.split(","));
//     * }
//
//     * Helper method to set choices from list (could be added):
//     * public void setChoicesFromList(List<String> choiceList) {
//     *     this.choices = String.join(",", choiceList);
//     * }
//     */
//}














// Package declaration - organizes classes within the model package
package com.almubaraksuleiman.cbts.examiner.model;

// Import statements - JPA annotations, Lombok utilities, and Jackson for JSON handling
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Enhanced Question entity with comprehensive question management features.
 * Represents a single question within a test in the Computer-Based Test (CBT) system.
 * Each question contains the question text, answer choices, correct answer, scoring information,
 * media attachments, and maintains a relationship with its parent test.
 *
 * This entity supports multiple question types, media attachments, and advanced
 * question configurations for comprehensive test creation.
 *
 * This entity is mapped to the "questions" table in the database and uses JPA annotations
 * for object-relational mapping along with Lombok for boilerplate code reduction.
 *
 * Key Features:
 * - Multiple question types (Multiple Choice, True/False, Essay, etc.)
 * - Media attachment support (Images, Videos, Audio)
 * - Advanced answer configurations
 * - Comprehensive validation and scoring
 * - Question ordering and organization
 *
 * @author Almubarak Suleiman
 * @version 2.0
 * @since 2025
 */
@Entity // Marks this class as a JPA entity (persistent domain object)
@Table(name = "questions") // Specifies the database table name
@Data // Lombok: generates getters, setters, toString, equals, and hashCode methods
@NoArgsConstructor // Lombok: generates a no-arguments constructor
@AllArgsConstructor // Lombok: generates a constructor with all fields as arguments
@Builder // Lombok: enables the builder pattern for object creation
public class Question {

    /**
     * Unique identifier for the question.
     * Auto-generated by the database using identity column strategy.
     * This is the primary key of the questions table.
     * Used for all question-related operations and references.
     */
    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-increment strategy
    private Long id;

    /**
     * The actual question text or prompt presented to the student.
     * Contains the problem, scenario, or query that the student must address.
     * This field should be clear, unambiguous, and complete.
     * Supports HTML formatting for rich text content.
     */
    @Column(nullable = false, length = 2000) // Increased length for comprehensive questions
    private String text;

    /**
     * The available answer choices for the question.
     * Stored as a JSON string for complex structures or comma-separated for simple choices.
     * Example formats:
     * - JSON: ["Option A", "Option B", "Option C", "Option D"]
     * - CSV: "Option A,Option B,Option C,Option D"
     *
     * For multiple choice questions, this contains all possible options.
     * For true/false questions, this might contain ["True", "False"].
     * For matching questions, contains JSON with left-right pairs.
     */
    @Column(length = 2000) // Increased length for complex choice structures
    private String choices;

    /**
     * The correct answer to the question.
     * Format depends on question type:
     * - Multiple Choice: single option text
     * - Multiple Select: comma-separated correct options
     * - True/False: "True" or "False"
     * - Fill in Blank: exact expected answer
     * - Essay: model answer or guidelines
     * - Matching: JSON with correct pair mappings
     */
    @Column(length = 1000)
    private String correctAnswer;

    /**
     * The type of question, determining how it should be presented and evaluated.
     * Uses the QuestionType enum to enforce valid question types.
     * Defaults to MULTIPLE_CHOICE for convenience and backward compatibility.
     */
    @Enumerated(EnumType.STRING) // Store enum values as strings in database
    @Column(nullable = false)
    private QuestionType type = QuestionType.MULTIPLE_CHOICE;

    /**
     * The maximum marks or points awarded for answering this question correctly.
     * Used in score calculation and grading.
     * Defaults to 1.0 point for standard questions.
     * Supports decimal values for partial credit scenarios.
     */
    @Column(nullable = false)
    private Double maxMarks = 1.0;

    /**
     * The test that this question belongs to.
     * Many-to-One relationship: Many questions can belong to one test.
     * Uses lazy fetching to improve performance (data loaded only when accessed).
     * The foreign key column "test_id" cannot be null, ensuring every question has a parent test.
     *
     * JsonIgnore prevents circular references during JSON serialization.
     * ToString.Exclude prevents infinite loops in toString() method.
     */
    @ManyToOne(fetch = FetchType.LAZY) // Many questions to one test relationship with lazy loading
    @JoinColumn(name = "test_id", nullable = false) // Foreign key column with not-null constraint
    @ToString.Exclude // Lombok: exclude from toString() to prevent circular references
    @JsonIgnore // Jackson: ignore during JSON serialization to prevent circular references
    private Test test;

    /**
     * Media type associated with the question.
     * Determines what type of media file is attached to the question.
     * Values: IMAGE, VIDEO, AUDIO, NONE
     * Used to enhance questions with visual or audio content.
     */
    @Enumerated(EnumType.STRING)
    @Column
    private MediaType mediaType = MediaType.NONE;

    /**
     * Media file path or URL for attached media content.
     * For images: "/uploads/images/question1.jpg"
     * For video: "/uploads/videos/demo.mp4"
     * For audio: "/uploads/audio/explanation.mp3"
     * Can be relative paths for local storage or full URLs for external resources.
     */
    @Column(length = 500)
    private String mediaPath;

    /**
     * Media caption or description for accessibility and context.
     * Provides alternative text for images, descriptions for videos/audio.
     * Important for accessibility compliance and user understanding.
     */
    @Column(length = 500)
    private String mediaCaption;

    /**
     * Order or sequence number of the question within the test.
     * Used to control the presentation order of questions to students.
     * Lower numbers appear first, null values typically appear last.
     */
    private Integer questionOrder;

    /**
     * Difficulty level of the question for adaptive testing and analytics.
     * Can be used for question selection algorithms and performance analysis.
     */
    @Enumerated(EnumType.STRING)
    private DifficultyLevel difficulty;

    /**
     * Explanation of the correct answer for review and learning purposes.
     * Displayed to students after they complete the test or during review sessions.
     * Helps in the learning process by explaining why answers are correct/incorrect.
     */
    @Column(length = 1500)
    private String explanation;

    /**
     * Category or topic of the question for organization and filtering.
     * Useful for categorizing questions by subject area, chapter, or concept.
     */
    private String category;

    /**
     * Time limit for this specific question in seconds (overrides test duration if set).
     * Allows for per-question timing in addition to overall test timing.
     * Null indicates no specific time limit for this question.
     */
    private Integer timeLimitSeconds;

    /**
     * Flag indicating whether partial credit is allowed for this question.
     * If true, students can receive partial marks for partially correct answers.
     * Particularly useful for multiple select and complex questions.
     */
    private Boolean allowPartialCredit = false;

    /**
     * Timestamp indicating when the question was created.
     * Automatically set when the question is first persisted.
     * Used for auditing, versioning, and tracking question lifecycle.
     */
    @CreationTimestamp
    private LocalDateTime createdAt;

    /**
     * Timestamp indicating when the question was last modified.
     * Automatically updated when the question is modified.
     * Helps track recent changes and maintain question history.
     */
    @UpdateTimestamp
    private LocalDateTime updatedAt;

    // Helper Methods

    /**
     * Converts the choices string to a List of individual choice options.
     * Handles both comma-separated and JSON array formats.
     *
     * @return List<String> List of choice options, empty list if no choices
     */
    @Transient
    public List<String> getChoicesAsList() {
        if (choices == null || choices.trim().isEmpty()) {
            return new ArrayList<>();
        }

        // Handle JSON array format
        if (choices.trim().startsWith("[") && choices.trim().endsWith("]")) {
            try {
                // Simple JSON parsing - for production use a JSON library
                String clean = choices.trim().substring(1, choices.length() - 1);
                return List.of(clean.split("\",\""));
            } catch (Exception e) {
                // Fall back to comma separation
                return List.of(choices.split(","));
            }
        }

        // Handle comma-separated format
        return List.of(choices.split(","));
    }

    /**
     * Sets choices from a List of options, converting to appropriate string format.
     *
     * @param choiceList List of choice options to set
     */
    @Transient
    public void setChoicesFromList(List<String> choiceList) {
        if (choiceList == null || choiceList.isEmpty()) {
            this.choices = null;
            return;
        }

        // Use JSON format for complex choices, comma-separated for simple ones
        if (choiceList.stream().anyMatch(choice -> choice.contains(",") || choice.contains("\""))) {
            this.choices = "[\"" + String.join("\",\"", choiceList) + "\"]";
        } else {
            this.choices = String.join(",", choiceList);
        }
    }

    /**
     * Validates if the question configuration is consistent with its type.
     *
     * @return boolean True if the question configuration is valid
     */
    @Transient
    public boolean isValidConfiguration() {
        if (text == null || text.trim().isEmpty()) {
            return false;
        }

        switch (type) {
            case MULTIPLE_CHOICE:
            case MULTIPLE_SELECT:
                return choices != null && !choices.trim().isEmpty() &&
                        correctAnswer != null && !correctAnswer.trim().isEmpty();
            case TRUE_FALSE:
                return "True".equals(correctAnswer) || "False".equals(correctAnswer);
            case FILL_IN_THE_BLANK:
            case ESSAY:
                return correctAnswer != null && !correctAnswer.trim().isEmpty();
            case MATCHING:
                return choices != null && !choices.trim().isEmpty();
            default:
                return true;
        }
    }

    /**
     * Checks if media is attached to this question.
     *
     * @return boolean True if media is attached, false otherwise
     */
    @Transient
    public boolean hasMedia() {
        return mediaType != null && mediaType != MediaType.NONE &&
                mediaPath != null && !mediaPath.trim().isEmpty();
    }

    /**
     * Gets the media file extension if media is attached.
     *
     * @return String File extension or null if no media
     */
    @Transient
    public String getMediaFileExtension() {
        if (!hasMedia()) {
            return null;
        }

        int lastDot = mediaPath.lastIndexOf('.');
        if (lastDot > 0 && lastDot < mediaPath.length() - 1) {
            return mediaPath.substring(lastDot + 1).toLowerCase();
        }
        return null;
    }

    // Enums



    /**
     * Builder pattern example for creating Question instances.
     * Demonstrates how to use the Lombok @Builder annotation with custom defaults.
     * Example Usage:
     * {@code
     * Question mathQuestion = Question.builder()
     *     .text("What is the value of π (pi) to two decimal places?")
     *     .choices("3.14,3.41,3.16,3.18")
     *     .correctAnswer("3.14")
     *     .type(QuestionType.MULTIPLE_CHOICE)
     *     .maxMarks(1.0)
     *     .mediaType(MediaType.IMAGE)
     *     .mediaPath("/uploads/images/pi-diagram.jpg")
     *     .mediaCaption("Diagram showing the concept of pi")
     *     .difficulty(DifficultyLevel.EASY)
     *     .explanation("Pi is approximately 3.14 for most basic calculations.")
     *     .category("Mathematics")
     *     .test(parentTest)
     *     .build();
     * }
     */
}