// Package declaration - organizes classes within the model package
package com.almubaraksuleiman.cbts.examiner.model;

// Import statements - JPA annotations and Lombok utilities
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Enhanced Test entity with comprehensive test window management.
 * Represents an exam or test in the Computer-Based Test (CBT) system with advanced
 * scheduling, access control, and security features.
 *
 * Each Test contains a set of questions and metadata such as title, description, duration,
 * and configuration settings for test administration. The enhanced version includes
 * test window management, IP restrictions, and secure browser requirements.
 *
 * This entity is mapped to the "tests" table in the database and uses JPA annotations
 * for object-relational mapping along with Lombok for boilerplate code reduction.
 *
 * Key Features:
 * - Test scheduling with start/end times and buffers
 * - IP-based access restrictions
 * - Secure browser requirements
 * - Multiple time enforcement modes
 * - Attempt limits and access controls
 *
 * @author Almubarak Suleiman
 * @version 2.0
 * @since 2025
 */
@Entity // Marks this class as a JPA entity (persistent domain object)
@Table(name = "tests") // Specifies the database table name
@Data // Lombok: generates getters, setters, toString, equals, and hashCode methods
@NoArgsConstructor // Lombok: generates a no-arguments constructor
@AllArgsConstructor // Lombok: generates a constructor with all fields as arguments
@Builder // Lombok: enables the builder pattern for object creation
public class Test {

    /**
     * Unique identifier for the test.
     * Auto-generated by the database using identity column strategy.
     * This is the primary key of the tests table.
     * Used for all test-related operations and references.
     */
    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-increment strategy
    private Long id;

    /**
     * Name or title of the test (e.g., "Mathematics Final Exam 2025").
     * Must be unique across all tests and cannot be null.
     * This field is indexed for efficient searching.
     * Displayed to students and administrators throughout the system.
     */
    @Column(nullable = false) // Database column constraints
    private String title;

    /**
     * Number of questions each student will receive when taking the test.
     * If null, all questions in the test might be presented.
     * Useful for creating randomized test versions from a larger question pool.
     * Helps in creating different test versions for different student groups.
     */
    @Column(name = "number_of_questions") // Explicit column name mapping
    private Integer numberOfQuestions;

    /**
     * Flag indicating whether questions should be presented in random order.
     * If true, each student receives questions in a different sequence.
     * Enhances test security by reducing cheating opportunities.
     * Prevents students from sharing question sequences.
     */
    @Column(name = "randomize_questions") // Explicit column name mapping
    private Boolean randomizeQuestions;

    /**
     * Flag indicating whether answer choices (options A-D) should be shuffled.
     * If true, the order of choices is randomized for each question presentation.
     * Further enhances test security and prevents answer pattern memorization.
     * Makes it difficult for students to share specific answer patterns.
     */
    @Column(name = "randomize_options") // Explicit column name mapping
    private Boolean shuffleChoices;

    /**
     * Detailed description or instructions for the test.
     * Provides context, guidelines, or special instructions for examinees.
     * This field can contain HTML formatting for rich text display.
     * Displayed to students before they begin the test.
     */
    private String description; // Default column mapping (same name as field)

    /**
     * Time limit for completing the test, specified in minutes.
     * If null, the test may have no time limit (unlimited duration).
     * Important for timed examinations and automatic submission.
     * Enforced based on the timeEnforcement mode setting.
     */
    private Integer durationMinutes; // Default column mapping

    /**
     * Total maximum marks available in the test.
     * Represents the sum of maximum marks from all questions.
     * Used for score calculation and grading purposes.
     * Displayed to students as the total possible score.
     */
    private Integer totalMarks; // Default column mapping

    /**
     * Publication status of the test.
     * If false, the test is in draft mode and not available to students.
     * If true, the test is published and available for administration.
     * Default value is false (unpublished) when creating new tests.
     * Controls whether students can see and access the test.
     */
    private Boolean published = false; // Default value set to false

    /**
     * Collection of questions associated with this test.
     * Uses lazy fetching for performance and cascade all for data integrity.
     * Represents the one-to-many relationship between test and questions.
     * Questions are managed and displayed in the context of their parent test.
     */
    @OneToMany(mappedBy = "test", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private List<Question> questions;

    /**
     * Minimum score required to pass the test.
     * Represented as an absolute value (not percentage).
     * Used to determine if a student has passed or failed.
     * If null, passing criteria may be determined elsewhere in the system.
     */
    private Integer passingScore;

    /**
     * Timestamp indicating when the test was created.
     * Automatically set by Hibernate when the entity is first persisted.
     * Used for auditing, reporting, and display purposes.
     * Cannot be modified manually by users.
     */
    @CreationTimestamp
    private LocalDateTime createdAt;

    /**
     * Timestamp indicating when the test was last updated.
     * Automatically updated by Hibernate when the entity is modified.
     * Used for auditing, reporting, and tracking changes.
     * Helps identify the most recent modifications to the test.
     */
    @UpdateTimestamp
    private LocalDateTime updatedAt;

    /**
     * Examiner who created this test.
     * Represents the many-to-one relationship with Examiner entity.
     * Used for access control and ownership tracking.
     * Examiners can only manage tests they created (unless admin).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by", nullable = false)
    private Examiner createdBy;

    // NEW: Test Window Configuration Fields

    /**
     * Scheduled start date and time for the test availability.
     * If null, test is available immediately upon publication.
     * Used to control when students can begin taking the test.
     * Combined with startBufferMinutes for early access configuration.
     */
    @Column(name = "scheduled_start_time")
    private LocalDateTime scheduledStartTime;

    /**
     * Scheduled end date and time for the test availability.
     * If null, test remains available indefinitely.
     * Used to control when the test becomes unavailable to students.
     * Combined with endBufferMinutes for grace period configuration.
     */
    @Column(name = "scheduled_end_time")
    private LocalDateTime scheduledEndTime;

    /**
     * Time limit enforcement mode for the test duration:
     * STRICT - Test automatically submits when time expires
     * FLEXIBLE - Students can continue but answers are marked as overtime
     * NONE - No time enforcement, students can take as long as needed
     * Defaults to STRICT for most examination scenarios.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "time_enforcement")
    private TimeEnforcementMode timeEnforcement;

    /**
     * Maximum allowed attempts for this test.
     * Null or 0 indicates unlimited attempts.
     * Used to control how many times a student can take the test.
     * Helps prevent abuse and ensures fair assessment conditions.
     */
    @Column(name = "max_attempts")
    private Integer maxAttempts;

    /**
     * Time buffer in minutes before scheduled start when test becomes available.
     * Useful for allowing students to join early and get prepared.
     * Example: 5 minutes buffer allows access 5 minutes before official start time.
     * Helps reduce server load by spreading student connections over time.
     */
    @Column(name = "start_buffer_minutes")
    private Integer startBufferMinutes;

    /**
     * Time buffer in minutes after scheduled end when submissions are still accepted.
     * Helps accommodate network delays, technical issues, or slow submissions.
     * Example: 5 minutes buffer allows submissions 5 minutes after official end time.
     * Provides grace period for students experiencing last-minute difficulties.
     */
    @Column(name = "end_buffer_minutes")
    private Integer endBufferMinutes;

    /**
     * IP restriction for test access.
     * Comma-separated list of allowed IP ranges or specific IPs.
     * Supports exact IPs, wildcards, CIDR notation, and IP ranges.
     * Example: "192.168.1.1, 192.168.1.0/24, 10.0.0.1-10.0.0.100"
     * Used to restrict test access to specific locations or networks.
     */
    @Column(name = "allowed_ips", length = 1000)
    private String allowedIPs;

    /**
     * Browser restrictions for security.
     * If true, requires secure browser with disabled developer tools.
     * Prevents cheating by disabling right-click, copy-paste, and developer tools.
     * Typically used for high-stakes examinations and certifications.
     * May require special browser configurations or dedicated kiosk applications.
     */
    @Column(name = "secure_browser")
    private Boolean secureBrowser;

    // Transient Methods (Calculated Fields)

    /**
     * Determines the current status of the test based on schedule and settings.
     * This is a calculated field and not persisted in the database.
     * Provides real-time status information for display and logic decisions.
     *
     * @return TestStatus The current status of the test (DRAFT, SCHEDULED, ACTIVE, or EXPIRED)
     *
     * Status Logic:
     * - DRAFT: Test is not published
     * - SCHEDULED: Published but scheduled start time is in the future
     * - ACTIVE: Published and currently within the accessible time window
     * - EXPIRED: Published but scheduled end time has passed
     */
    @Transient
    public TestStatus getCurrentStatus() {
        LocalDateTime now = LocalDateTime.now();

        if (!Boolean.TRUE.equals(published)) {
            return TestStatus.DRAFT;
        }

        if (scheduledStartTime != null && now.isBefore(scheduledStartTime)) {
            return TestStatus.SCHEDULED;
        }

        if (scheduledEndTime != null && now.isAfter(scheduledEndTime)) {
            return TestStatus.EXPIRED;
        }

        return TestStatus.ACTIVE;
    }

    /**
     * Checks if the test is currently accessible based on schedule and buffers.
     * Considers publication status, scheduled times, and buffer configurations.
     * Used to determine if a student can start or continue the test.
     *
     * @return boolean True if the test is currently accessible, false otherwise
     *
     * Accessibility Logic:
     * 1. Test must be published
     * 2. Current time must be after effective start time (considering buffer)
     * 3. Current time must be before effective end time (considering buffer)
     * 4. If no scheduled times, test is always accessible when published
     */
    @Transient
    public boolean isCurrentlyAccessible() {
        if (!Boolean.TRUE.equals(published)) {
            return false;
        }

        LocalDateTime now = LocalDateTime.now();
        LocalDateTime effectiveStart = scheduledStartTime;
        LocalDateTime effectiveEnd = scheduledEndTime;

        // Apply start buffer (allow early access)
        if (effectiveStart != null && startBufferMinutes != null) {
            effectiveStart = effectiveStart.minusMinutes(startBufferMinutes);
        }

        // Apply end buffer (allow late submissions)
        if (effectiveEnd != null && endBufferMinutes != null) {
            effectiveEnd = effectiveEnd.plusMinutes(endBufferMinutes);
        }

        boolean afterStart = effectiveStart == null || !now.isBefore(effectiveStart);
        boolean beforeEnd = effectiveEnd == null || !now.isAfter(effectiveEnd);

        return afterStart && beforeEnd;
    }

    // Enums

    /**
     * Enumeration defining time enforcement modes for test duration.
     * Controls how the system handles time expiration during tests.
     */
    public enum TimeEnforcementMode {
        /**
         * Strict enforcement - test automatically submits when time expires.
         * Students cannot continue answering after time limit.
         * Most secure option for timed examinations.
         */
        STRICT,

        /**
         * Flexible enforcement - students can continue but answers are marked overtime.
         * Allows completion but tracks which answers were submitted after time limit.
         * Useful for accommodating slow readers or technical issues.
         */
        FLEXIBLE,

        /**
         * No time enforcement - students can take as long as needed.
         * Duration is recorded but not enforced.
         * Suitable for untimed practice tests or self-paced learning.
         */
        NONE
    }

    /**
     * Enumeration defining possible test statuses.
     * Represents the current state of the test in its lifecycle.
     */
    public enum TestStatus {
        /**
         * Test is not published and only visible to creators/admins.
         * Can be edited and configured but not taken by students.
         */
        DRAFT,

        /**
         * Test is published but scheduled start time is in the future.
         * Students can see it's scheduled but cannot start yet.
         */
        SCHEDULED,

        /**
         * Test is published and currently within its accessible time window.
         * Students can start and take the test.
         */
        ACTIVE,

        /**
         * Test is published but scheduled end time has passed.
         * Students can no longer start the test.
         */
        EXPIRED
    }

    /**
     * Builder pattern example for creating Test instances.
     * Demonstrates how to use the Lombok @Builder annotation.
     *
     * Example Usage:
     * {@code
     * Test mathTest = Test.builder()
     *     .title("Mathematics Final Exam")
     *     .description("Comprehensive mathematics examination covering algebra and calculus")
     *     .durationMinutes(120)
     *     .numberOfQuestions(50)
     *     .randomizeQuestions(true)
     *     .shuffleChoices(true)
     *     .totalMarks(100)
     *     .passingScore(60)
     *     .published(true)
     *     .scheduledStartTime(LocalDateTime.of(2025, 6, 15, 9, 0))
     *     .scheduledEndTime(LocalDateTime.of(2025, 6, 15, 11, 0))
     *     .timeEnforcement(TimeEnforcementMode.STRICT)
     *     .maxAttempts(1)
     *     .startBufferMinutes(5)
     *     .endBufferMinutes(5)
     *     .secureBrowser(true)
     *     .build();
     * }
     */
}