package com.almubaraksuleiman.cbts.admin.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.validator.constraints.Length;

/**
 * Entity class representing an Administrator in the CBTS (Computer-Based Test System).

 * This class maps to the "admin" table in the database and represents system administrators
 * who have elevated privileges for managing exams, questions, users, and system configuration.

 * The entity includes:
 * - Unique identification and authentication credentials
 * - Email verification status for security
 * - Lombok annotations for boilerplate code reduction
 *
 * @author Almubarak Suleiman
 * @version 1.0
 * @since 2025
 */
@Entity
@Table(name = "admin") // Explicitly maps to "admin" table in database
@Data // Lombok: Generates getters, setters, toString, equals, and hashCode
@NoArgsConstructor // Lombok: Generates no-args constructor
@AllArgsConstructor // Lombok: Generates all-args constructor
public class Admin {

    /**
     * Primary key identifier for the Admin entity.
     * Uses database identity generation for automatic ID assignment.
     *
     * @apiNote This field is automatically generated by the database upon persistence.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-increment strategy
    private Long id;

    /**
     * Unique username for administrator authentication and identification.
     * Must be unique across all admin accounts and cannot be null.
     *
     * @constraint Unique across the system, not nullable, 3-20 characters,
     * @usage Used for login authentication and admin identification
     */
    @NotBlank(message = "Username is required")
    @Size(min = 3, max = 20, message = "Username must be between 3 and 20 characters")
    @Pattern(regexp = "^[a-zA-Z0-9_]+$", message = "Username can only contain letters, numbers, and underscores")
    @Column(unique = true, nullable = false) // Database unique constraint
    private String username;

    /**
     * Hashed password for administrator authentication.
     * Stores BCrypt-hashed password for secure authentication.
     * Must be unique (though typically hashes will be different) and cannot be null.
     *
     * @security Should always be stored in hashed format using BCrypt
     * @constraint Not nullable, technically unique but primarily for hashed resource
     */
    @NotBlank(message = "Password is required")
    @Size(min = 8, message = "Password must be at least 8 characters long")
    @Column(unique = true, nullable = false) // Unique constraint for hashed passwords
    private String password;

    /**
     * Email verification status flag.
     * Indicates whether the administrator's email address has been verified.
     * Defaults to false upon account creation and must be set to true after verification.
     *
     * @default false (unverified upon account creation)
     * @businessRule Admin accounts require email verification before full system access
     */
    @Column(nullable = false) // Cannot be null, defaults to false
    private boolean verified = false; // Initial state: unverified

    /**
     * Unique email address for the administrator.
     * Used for communication, notifications, and account recovery.
     * Must be unique across all admin accounts and cannot be null.
     *
     * @constraint Unique across the system, not nullable
     * @validation Should be validated for proper email format
     */
    @Email(message = "Email should be a valid email address",
            regexp = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$")
    @Column(unique = true, nullable = false) // Database unique constraint
    @Email
    private String email;

    @Column
    String firstName;

    @Column
    String middleName;

    @Column
    String lastName;


    @Column
    String department;

    // Note: Additional fields that could be considered for future enhancement:
    // - firstName and lastName for personal identification
    // - phoneNumber for additional contact information
    // - role or permissionLevel for granular access control
    // - lastLoginDate for security auditing
    // - accountCreatedDate for account management
    // - profileImageUrl for admin profile pictures
}